### ISSUE TITLE
Application not properly working when running unit tests (state not working)

### ISSUE THREAD

**Issue by jmevel** [PacktPublishing/Learn-React-with-TypeScript-2nd-Edition#2]
When running unit tests with Jest, the state is actually not working like it should.

A more complete implementation of the test `should call onCheckedIdsChange when clicked` could be as follows:

```js
test("should call onCheckedIdsChange when clicked", async () => {
  const user = userEvent.setup();
  let calledWith: IdValue[] | undefined = undefined;
  render(
    <Checklist
      data={[
        { id: 1, name: "Lucy", role: "Manager" },
        { id: 2, name: "Bob", role: "Developer" },
        { id: 3, name: "Alice", role: "UX Designer" },
      ]}
      id="id"
      primary="name"
      secondary="role"
      onCheckedIdsChange={(checkedIds) => (calledWith = checkedIds)}
    />
  );
  await user.click(screen.getByTestId("Checklist__input__1"));
  await user.click(screen.getByTestId("Checklist__input__3"));
  expect(calledWith).toStrictEqual([1, 3]);
}, 60_000); // increased timeout to give us time to debug
```

As you can see, checking 2 items fails.
The reason is in `useChecked.ts` when doing `const [resolvedCheckedIds, setResolvedCheckedIds] = useState<IdValue[]>(checkedIds || []);` the `resolvedCheckedIds` never no values even though there should be on the second call.

I haven't find the solution to this problem.
How to fix this please? Having a working state in unit tests is a MUST HAVE otherwise those tests are simply useless.

Thanks for your answer

**Comment by carlrip** [comment]
As soon as you specify `onCheckedIdsChange`, `Checklist` kind of assumes `checkedIds` is going to be controlled.

The fix is to always set the internal state in `useChecked.handleCheckChange` - i.e. bring the call to `setResolvedCheckedIds` outside of the `else` branch:

```
const handleCheckChange = (checkedId: IdValue) => () => {
   const newCheckedIds = getNewCheckedIds(resolvedCheckedIds, checkedId);
   if (onCheckedIdsChange) {
      onCheckedIdsChange(newCheckedIds);
   }
   setResolvedCheckedIds(newCheckedIds);
};
```

**Comment by jmevel** [comment]
> As soon as you specify `onCheckedIdsChange`, `Checklist` kind of assumes `checkedIds` is going to be controlled.
> 
> The fix is to always set the internal state in `useChecked.handleCheckChange` - i.e. bring the call to `setResolvedCheckedIds` outside of the `else` branch:
> 
> ```
> const handleCheckChange = (checkedId: IdValue) => () => {
>    const newCheckedIds = getNewCheckedIds(resolvedCheckedIds, checkedId);
>    if (onCheckedIdsChange) {
>       onCheckedIdsChange(newCheckedIds);
>    }
>    setResolvedCheckedIds(newCheckedIds);
> };
> ```

Hey Carl, thanks a lot for your answer.
Quite busy recently but I'll have a look at your solution as soon as I have a bit of free time !

**Comment by jmevel** [comment]
Finally got the time to check and understand your solution. 
Makes perfect sense!

Thanks a lot
